<h1>Erro Encontrado</h1>
<h2><?php echo $this->message ?></h2>
<?php if ($this->exception != null) : ?>
<h2>Informações Adicionais</h2>
<p>
    <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
</p>
<h3>Pilha de Chamadas</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>
<h3>Parâmetros da Requisição</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif ?>