<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8"/>
		<script type="text/javascript" src="<?php echo $this->baseUrl ?>/js/prototype.js"></script>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/css/default.css"/>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/css/default-tableless.css"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl ?>/img/favicon.ico" />
		<?php echo $this->headTitle() ?> 
	</head>
	<body>
		<div id="layout">
			<div id="banner">
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/banner-l.jpg" width="250" height="150"/>
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/banner-c-l.jpg" width="250" height="150"/>
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/banner-c-r.jpg" width="250" height="150"/>
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/banner-r.jpg" width="250" height="150"/>
			</div>
			<div id="menu">
				<div>
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/menu-main.jpg" width="200" height="31"/>
<!-- Menu:    Begin -->
<?php echo $this->render('menus/default.phtml') ?> 
<!-- Menu:    End   -->
				</div>
				<div>
<img src="<?php echo $this->baseUrl ?>/img/layouts/default/menu-search.jpg" width="200" height="31"/>
				</div>
			</div>
			<div id="content">
<!-- Content: Begin -->
<?php echo $this->barra ?>
<?php echo $this->toolbar ?>
<?php echo $this->layout()->content ?> 
<!-- Content: End   -->
			</div>
			<div id="footer"></div>
		</div>
	</body>
</html>
