<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8"/>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/css/login.css"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl ?>/img/favicon.ico" />
		<?php echo $this->headTitle() ?>
	</head>
	<body>
		<div id="login">
			<div><img src="<?php echo $this->baseUrl ?>/img/layouts/login/login-t.jpg" width="300" height="32"/></div>
			<div id="form">
				<?php echo $this->layout()->content ?> 
			</div>
			<div><img src="<?php echo $this->baseUrl ?>/img/layouts/login/login-d.jpg" width="300" height="45"/></div>
		</div>
	</body>
</html>
