<h2>Listar Referências</h2>
<?php if (count($this->messages) > 0) : ?>
<ul>
<?php foreach ($this->messages as $message) : ?>
    <li><?php echo $this->escape($message) ?></li>
<?php endforeach ?>
</ul>
<?php endif ?>
<table>
    <thead>
        <tr>
            <td>Tipo</td>
            <td>Identificador</td>
            <td>Informações</td>
            <td><a href="<?php echo $this->url(array('action' => 'create')) ?>">Adicionar</a></td>
        </tr>
    </thead>
    <tbody>
<?php if (count($this->result) > 0) : ?>
<?php foreach ($this->result as $element) : ?>
        <tr>
            <td><?php echo $this->escape($element->tipo) ?></td>
            <td><?php echo $this->escape($element->identificador) ?></td>
            <td><?php echo $this->escape($element->conteudo) ?></td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'edit', 'idreferencia' => $element->idreferencia)) ?>">Editar</a>
                <a href="<?php echo $this->url(array('action' => 'remove', 'idreferencia' => $element->idreferencia))?>">Remover</a>
            </td>
        </tr>
<?php endforeach ?>
<?php else : ?>
        <tr>
            <td colspan="4">Lista Vazia</td>
        </tr>
<?php endif ?>
    </tbody>
</table>