<table>
	<tr>
		<th width="60" title="Código"><a href="?order=codigo">Cód</a></th>
		<th title="Nome do Curso"><a href="?order=nome">Nome</a></th>
		<th width="90" title="Investimento"><a href="?order=investimento">Preço<a/></th>
		<th width="40" title="Número Mínimo de Alunos"><a href="?order=minimo">Mín</a></th>
		<th width="40" title="Número Máximo de Alunos"><a href="?order=maximo">Máx</a></th>
		<th width="20"></th>
		<th width="20"></th>
	</tr>
<?php if(count($this->cursos) > 0) : ?>
<?php $class = '' ?>
<?php foreach($this->cursos as $curso) : ?>
<?php $class = $class == '' ? 'linha' : '' ?>
	<tr class="<?php echo $class ?>">
		<td><?php echo $this->escape($curso['codigo']) ?></td>
		<td><?php echo $this->escape($curso['nome']) ?></td>
		<td><?php echo $this->escape($curso['investimento']) ?></td>
		<td><?php echo $this->escape($curso['minimo']) ?></td>
		<td><?php echo $this->escape($curso['maximo']) ?></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/prod/curso/edit/id/<?php echo $curso['id'] ?>">V</a></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/prod/curso/delete/id/<?php echo $curso['id'] ?>">X</a></td>
	</tr>
<?php endforeach ?>
<?php else : ?>
	<tr>
		<td colspan="7" align="center">Sem Cadastro</td>
	</tr>
<?php endif ?>
</table>