<?php echo $this->doctype() . PHP_EOL ?>
<html>
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->dojo()->enable()->setDjConfigOption('parseOnLoad', true)
    ->registerModulePath('app', $this->baseUrl('/scripts/app'))->requireModule('app') ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/scripts/app/layout/layout.css')) ?>
<script type="text/javascript">
var sistema;
dojo.ready(function(){
    sistema = new app();
});
</script>
</head>
<body class="claro">
<!-- dijit layout -->
<div id="layout-main" dojoType="dijit.layout.BorderContainer">
    <div id="layout-center" dojoType="dijit.layout.BorderContainer" region="center">
        <div id="layout-tabcontainer" dojoType="dijit.layout.TabContainer" region="center">
            <div id="layout-content" dojoType="dijit.layout.ContentPane" title="Sistema de Artigos">
<!-- conteúdo -->
<?php echo $this->layout()->content ?>
<!-- conteúdo -->
            </div>
        </div>
        <div id="layout-output" dojoType="dijit.layout.ContentPane" region="bottom">&nbsp;</div>
    </div>
    <div id="layout-leading" dojoType="dijit.layout.BorderContainer" region="leading">
        <div id="layout-logo" dojoType="dijit.layout.ContentPane" region="top">Top Logo</div>
        <div id="layout-menu" dojoType="dijit.layout.AccordionContainer" region="center">
            <div id="layout-docs" dojoType="dijit.layout.ContentPane" title="Artigos">
<!-- documentos -->
&nbsp;
<!-- documentos -->
            </div>
            <div id="layout-config" dojoType="dijit.layout.ContentPane" title="Configurações">
<!-- configurações -->
<?php echo $this->layout()->render('layout/config') ?>
<!-- configurações -->
            </div>
        </div>
    </div>
</div>
</body>
</html>