<h1><?php echo $this->titulo ?></h1>
<p>
	A página <span><?php echo $this->pagina ?></span> foi solicitada porém ela ocasionou um erro.
	Este erro pode ter sido gerado por alguma informação que o sistema não processou
	ou uma tentativa de acesso através de uma página inexistente.
</p>
<p>
	Clique <a href="<?php echo $this->baseUrl ?>/">aqui</a> para voltar à página principal.
</p>
<?php if(!is_null($this->id)) : ?>
<p class="note">
	<span>Código do Erro: <?php echo $this->id ?></span><br/>
	O erro gerado foi gravado no banco de dados e retornou um código. Por favor, anote este número
	e informe ao administrador na próxima visita do mesmo.
</p>
<?php endif; ?>
