<table class="grid">
    <tr>
        <th width="30">#</th>
        <th>Nome</th>
        <th width="100">Usuário</th>
        <th width="50">Ativo</th>
        <th width="60">
            <a href="<?php echo $this->url(array('action' => 'create')) ?>">
                <img alt="Adicionar" title="Adicionar" src="<?php echo $this->baseUrl('/themes/admin/images/add.png') ?>" />
            </a>
        </th>
    </tr>
<?php if (count($this->result) > 0) : ?>
<?php foreach ($this->result as $element) : ?>
    <tr>
        <td><?php echo $element->iduser ?></td>
        <td><?php echo $element->displayname ?></td>
        <td><?php echo $element->username ?></td>
        <td><?php echo $element->active ? 'Sim' : 'Não' ?></td>
        <td>
            <a href="<?php echo $this->url(array('action' => 'update', 'iduser' => $element->iduser)) ?>">
                <img alt="Editar" title="Editar" src="<?php echo $this->baseUrl('/themes/admin/images/edit.png') ?>" />
            </a>
            <a href="<?php echo $this->url(array('action' => 'delete', 'iduser' => $element->iduser)) ?>">
                <img alt="Remover" title="Remover" src="<?php echo $this->baseUrl('/themes/admin/images/delete.png') ?>" />
            </a>
        </td>
    </tr>
<?php endforeach ?>
<?php else : ?>
    <tr>
        <td colspan="5">Sem Resultados</td>
    </tr>
<?php endif ?>
</table>