<?php echo $this->doctype() ?>
<html>
    <head>
<!-- Head Start    -->
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->dojo()->addOnLoad('function(){ system.init() }')->addStylesheetModule('dijit.themes.claro') ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/system.css')) ?>
<?php echo $this->headScript()->appendFile($this->baseUrl('/js/system/system.js')) ?>
<!-- Head End      -->
    </head>
    <body class="claro">
        <div id="main">
            <div id="top">
                <h1>Wanderson Camargo</h1>
            </div>
            <div id="content">
<!-- Content Start -->
<?php echo $this->layout()->content ?>
<!-- Content End   -->
            </div>
        </div>
    </body>
</html>