<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- Head Begin -->
<?php echo $this->headMeta()->setIndent(4) . PHP_EOL ?>
<?php echo $this->headTitle()->setIndent(4) . PHP_EOL ?>
<?php
    echo $this->headLink()->setIndent(4)
        ->appendStylesheet($this->baseUrl('/css/blueprint/screen.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/css/blueprint/fancy-type/screen.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/css/blueprint/print.css'), 'print')
        ->appendStylesheet($this->baseUrl('/themes/layout/css/layout.css'))
        ->appendStylesheet($this->baseUrl('/themes/layout/css/screen.css')) . PHP_EOL
?>
<!-- Head End   -->
</head>
<body>
    <div class="layout-top">
        <div>&nbsp;</div>
    </div>
    <div class="container">
        <div id="header" class="span-24 last">
            <h1>Wanderson Camargo</h1>
            <div class="alt">Cientista da Computação e Programador Zend Framework</div>
            <hr />
        </div>
        <div id="content" class="span-17 colborder">
<!-- Content Begin -->
<?php echo $this->layout()->content ?>
<!-- Content End   -->
        </div>
        <div class="span-6 last">
<!-- Menu Begin -->
<div class="box">
    <ul>
        <li>Página Principal</li>
        <li>Artigos
            <ul>
                <li>Introdução ao Zend Framework</li>
                <li>Versionamento com Subversion</li>
                <li>Conheça o GNU/Linux</li>
            </ul>
        </li>
        <li>Sobre</li>
    </ul>
</div>
<h3 class="caps">Categorias</h3>
<div class="box">
    <ul>
        <li><a href="#" class="quiet">Linux</a></li>
        <li><a href="#" class="quiet">PHP</a></li>
        <li>Zend Framework</li>
    </ul>
</div>
<h3 class="caps">Nuvem de Visitas</h3>
<div class="box">
    <a href="#" class="quiet">zendframework</a>
    <a href="#" class="quiet">poo</a>
</div>
<h3 class="caps">Tecnologias</h3>
<div class="box techs">
    <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" />
</div>
<!-- Menu End   -->
        </div>
    </div>
    <div class="layout-bottom">
        <div>&nbsp;</div>
    </div>
</body>
</html>