<h1>Ops!</h1>
<h2><?php echo $this->message ?></h2>
<p>
    Alguma coisa aconteceu de errado para você estar visualizando esta página.
    Peço desculpas pelo ocorrido e informo que este erro foi contabilizado e
    logo será resolvido.
</p>
<p>
    Você pode ir para a página principal ou visitar outros destaques:
</p>
<ul>
    <li><a href="<?php echo $this->baseUrl('/') ?>" title="Ir para a Página Principal">Página Principal</a></li>
</ul>
<?php if (isset($this->exception)) : ?>
<h2>Informações para Depuração</h2>
<p>
    <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
</p>
<h3>Pilha de Chamadas</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>
<h3>Parâmetros da Requisição</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif ?>