<?php echo $this->doctype() . PHP_EOL ?>
<html>
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->dojo()->enable()->setDjConfigOption('parseOnLoad', true) ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/styles/layout.css')) ?>
</head>
<body class="claro">
<?php echo $this->navigation()->menu()->setMaxDepth(0) ?>
<?php echo $this->navigation()->breadcrumbs() ?>
<?php echo $this->layout()->content ?>
</body>
</html>