<?php echo $this->doctype() . PHP_EOL ?>
<html>
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->dojo()->enable()->setDjConfigOption('parseOnLoad', true)
    ->requireModule('dijit.layout.BorderContainer')
    ->requireModule('dijit.layout.ContentPane')
    ->requireModule('dijit.layout.AccordionContainer')
    ->requireModule('dijit.Toolbar')
    ->requireModule('dijit.form.Button')
    ->requireModule('dijit.layout.TabContainer')
    ->requireModule('dijit.Tree')
    ->requireModule('dojo.data.ItemFileReadStore')
    ->addLayer($this->baseUrl('/scripts/app/app.js')) ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/styles/system.css')) ?>
</head>
<body class="claro">
<div id="app" dojoType="dijit.layout.BorderContainer">
    <div id="layout-leading" dojoType="dijit.layout.BorderContainer" region="leading">
        <div dojoType="dijit.layout.AccordionContainer" region="center">
            <div dojoType="dijit.layout.ContentPane" title="Documentos">
<!-- Documentos -->
<div dojoType="dojo.data.ItemFileReadStore" jsId="storeDocuments" url="<?php echo $this->baseUrl('/artigo/store') ?>"></div>
<div dojoType="dijit.tree.ForestStoreModel" jsId="modelDocuments" store="storeDocuments" query="{}" rootLabel="Documentos" rootId="documents_root"></div>
<div id="documents" dojoType="dijit.Tree" model="modelDocuments"></div>
<!-- Final -->
            </div>
            <div dojoType="dijit.layout.ContentPane" title="Configurações">Configurações</div>
        </div>
    </div>
    <div dojoType="dijit.layout.BorderContainer" region="center">
        <div dojoType="dijit.Toolbar" region="top">
            <div dojoType="dijit.form.Button">Arquivo</div>
        </div>
        <div id="tab_container" dojoType="dijit.layout.TabContainer" region="center">
            <div dojoType="dijit.layout.ContentPane" title="Sistema de Artigos">
                Seja bem vindo!
            </div>
        </div>
        <div id="layout-console" dojoType="dijit.layout.ContentPane" region="bottom">&nbsp;</div>
    </div>
</div>
</body>
</html>