Ações:<br/>
<a href="<?php echo $this->baseUrl ?>/admin/resource/edit">Novo Módulo Cadastrado</a>
<p>
	Escrever sobre os módulos.
</p>
<table>
	<tr>
		<th>Nome</th>
		<th width="150">Identificador</th>
		<th width="20"></th>
		<th width="20"></th>
	</tr>
<?php foreach($this->resources as $resource) : ?>
	<tr>
		<td><?php echo $resource->name ?></td>
		<td><?php echo $resource->value ?></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/admin/resource/edit/id/<?php echo $resource->id ?>">V</a></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/admin/resource/delete/id/<?php echo $resource->id ?>">X</a></td>
	</tr>
<?php endforeach ?>
</table>
