<h2>Clientes</h2>
<script type="text/javascript">
	var interval;
	function searchClientes() {
		var nome     = $F('nome');
		var email    = $F('email');
		var telefone = $F('telefone');
		var url      = '<?php echo $this->baseUrl ?>/com/cliente/fast';
		var params   = 'nome=' + nome + '&email=' + email + '&telefone=' + telefone;
		try {
			var search = new Ajax.Updater('fast', url, {
				method: 'post',
				parameters: params,
			});
		}
		catch(e) {}
	}
	function search() {
		clearInterval(interval);
		interval = setTimeout('searchClientes()', 800);
	}
	search();
</script>
<?php echo $this->form ?>
<div id="fast"></div>
