# Makefile
# @author Wanderson Henrique Camargo Rosa

all:
	g++ -o trabalho05 -lglut -lGLU main.cpp source/Game.cpp source/Camera.cpp source/Object.cpp source/Cube.cpp source/Floor.cpp source/ObjectNode.cpp source/ObjectList.cpp source/BoundingBox.cpp source/Player.cpp

clean:
	rm -rf trabalho05