<table>
	<tr>
		<th width="60" title="Código"><a href="?order=codigo">Cód</a></th>
		<th title="Nome do Módulo"><a href="?order=nome">Nome</a></th>
		<th width="90" title="Investimento"><a href="?order=investimento">Preço</a></th>
		<th width="40" title="Carga Horária"><a href="?order=carga">CH</a></th>
		<th width="40" title="Número Mínimo de Alunos"><a href="?order=minimo">Mín</a></th>
		<th width="40" title="Número Máximo de Alunos"><a href="?order=maximo">Máx</a></th>
		<th width="20" title="Editar"></th>
		<th width="20" title="Deletar"></th>
	</tr>
<?php if(count($this->modulos) > 0) : ?>
<?php $class = '' ?>
<?php foreach($this->modulos as $modulo) : ?>
<?php $class = $class == '' ? 'linha' : '' ?>
	<tr class="<?php echo $class ?>">
		<td><?php echo $this->escape($modulo['codigo']) ?></td>
		<td><?php echo $this->escape($modulo['nome']) ?></td>
		<td>R$ <?php echo $this->escape($modulo['investimento']) ?></td>
		<td><?php echo $this->escape($modulo['carga']) ?>h</td>
		<td><?php echo $this->escape($modulo['minimo']) ?></td>
		<td><?php echo $this->escape($modulo['maximo']) ?></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/prod/modulo/edit/id/<?php echo $modulo['id'] ?>">V</a></td>
		<td align="center"><a href="<?php echo $this->baseUrl ?>/prod/modulo/delete/id/<?php echo $modulo['id'] ?>">X</a></td>
	</tr>
<?php endforeach ?>
<?php else : ?>
	<tr>
		<td colspan="8" align="center">Sem Cadastro</td>
	</tr>
<?php endif ?>
</table>
