<h1>Erro Encontrado</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)) : ?>
<h3>Informações de Erro:</h3>
<p>
    <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Pilha de Processamento</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>

<h3>Parâmetros de Requisição</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php else : ?>
<p>
    Olá! O sistema gerou um erro inesperado. Este problema foi registrado e logo
    será resolvido pelo administrador.
</p>
<?php endif ?>
