<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- Head Begin -->
<?php echo $this->headMeta()->setIndent(4) . PHP_EOL ?>
<?php echo $this->headTitle()->setIndent(4) . PHP_EOL ?>
<?php
    echo $this->headLink()->setIndent(4)
        ->appendStylesheet($this->baseUrl('/css/blueprint/screen.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/css/blueprint/fancy-type/screen.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/css/blueprint/print.css'), 'print')
        ->appendStylesheet($this->baseUrl('/themes/layout/css/layout.css')) . PHP_EOL
?>
<!-- Head End   -->
</head>
<body>
    <div class="layout-top">
        <div>&nbsp;</div>
    </div>
    <div class="container">
        <div id="header" class="span-24 last">
            <h1>Wanderson Camargo</h1>
            <div class="alt">Cientista da Computação e Programador Zend Framework</div>
            <hr />
        </div>
        <div class="span-17 colborder">
<!-- Content Begin -->
<?php echo $this->layout()->content ?>
<!-- Content End   -->
        </div>
        <div class="span-6 last">
            <div class="box">
                Right
            </div>
        </div>
        <div class="span-24 last">Footer</div>
    </div>
</body>
</html>