<?php $this->headMeta()->appendName('author', $this->escape($this->author)) ?>
<?php $this->headMeta()->appendName('description', $this->escape($this->description)) ?>
<div class="article">
    <h2><?php echo $this->escape($this->title) ?></h2>
    <div class="author">
        Por <span><?php echo $this->escape($this->author) ?></span> em <?php echo $this->date($this->created, Zend_Date::DATE_LONG) ?>
    </div>
    <div class="abstract">
<?php echo $this->escape($this->abstract) ?>
    </div>
<!-- Article Content Begin -->
<?php echo $this->content ?>
<!-- Article Content End   -->
</div>
<div class="posted"> 
<?php if ($this->category) : ?>
    Enviado em <a href="#"><?php echo $this->escape($category) ?></a>
<?php else : ?>
    Enviado sem Categoria
<?php endif ?>
</div> 